import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="markushgrapher",
    version="1.0.0",
    author="",
    author_email="",
    description="A Python library",
    long_description=long_description,
    long_description_content_type="text/markdown",
    packages=setuptools.find_packages(exclude=["tests.*", "tests"]),
    install_requires=[
        "torch==2.2.0",
        "torchvision==0.17.0",
        "torchaudio==2.2.0",
        "evaluate",
        "matplotlib",
        "Pillow",
        "pytorch_lightning",
        "sentencepiece",
        "accelerate",
        "scikit-learn",
        "evaluate",
        "wandb",
        "pytesseract",
        "pyyaml",
        "aiohttp",
        "s3fs",
        "fsspec==2023.6.0",
        "nltk",
        "rouge_score",
        "SmilesPE",
        "clearml",
        "opencv-python",
        "albumentations==1.4.2",
        "timm==0.4.12",
        "rdkit==2024.3.5",
        "rdkit-pypi==2022.9.5",
        "OpenNMT-py",
        "numpy==1.24.4",
        "accelerate==0.21.0", 
        "huggingface_hub",
        "markushgenerator @ git+https://git@github.com/DS4SD/MarkushGenerator.git",
    ],
    classifiers=[
        "Development Status :: 1 - Planning",
        "Intended Audience :: Developers",
        "Natural Language :: English",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
    ],
    python_requires='>=3.7',
)
