{
    "mdu_dataset": {
        module_name: "mdu_dataset",
        class_name: "MDU_Dataset",
        name: "mdu",
        type: "supervised",
        dataset_path: "./data/hf/m2s", # "m2s", "uspto-markush", "markushgrapher-synthetic", "markushgrapher-synthetic-training"
        encode_position: False, # False, True
        grounded_smiles: False, # False, True
        encode_index: True, # False, True
        encode_definition_group: False, # False, True
        condense_labels: True, # False, True
        augment_test: False, # False, True
        udop_tokenizer_only: False, # False, True
        normalize_bbox: False, # False, True
        training_dataset_name: "mdu_3008_aug", 
        mask_ratio: 1,
        task: "Question Answering",
        splits: ["train", "test"],
        load_from_cache: False,
        apply_ocr: False,
        stream: False
    },
}
