mdu_dataset:
  apply_ocr: false
  augment_test: false
  class_name: MDU_Dataset
  condense_labels: true
  dataset_path: ./data/hf/sample-images
  encode_definition_group: false
  encode_index: true
  encode_position: false
  grounded_smiles: false
  load_from_cache: false
  mask_ratio: 1
  module_name: mdu_dataset
  name: mdu
  normalize_bbox: true
  splits:
  - train
  - test
  stream: false
  task: Question Answering
  training_dataset_name: mdu_3008_aug
  type: supervised
  udop_tokenizer_only: false
