{
    model_name_or_path: ./models/markushgrapher-2, 
    tokenizer_path: auto,
    output_dir: auto,   
    datasets_config: ./config/datasets/datasets_predict.yaml,

    # Model config
    max_seq_length: 512,
    image_size: 512,
    max_seq_length_decoder: 512,
    model_type: UdopUnimodel, 
    architecture_variant:  me-lf-stack-1,
    beam_search: True,
    normalize_bbox: True, 

    # model weights
    use_pretrained_molscribe: True, 
    freeze_ocsr_encoder: True,
    freeze_vtl_decoder: False, 
    freeze_mlp_projector: False, 

    # Test config
    do_train: False,
    do_eval: False,
    do_predict: True,    
    dataloader_num_workers: 1,
    log_level: "DEBUG",
    viz_out_dir: auto,
    prediction_loss_only: True,
    label_names: ["labels"],      
    unit: word, 
    apply_ocr: False,
}
