{
    # Path config
    model_name_or_path: ./models/09_00_PM_October_30_2024/checkpoint-82500, 
    tokenizer_path: auto,
    output_dir: auto,   
    datasets_config: ./config/datasets/datasets_predict.yaml,

    # Model config
    max_seq_length: 512,
    image_size: 512,
    max_seq_length_decoder: 512,
    model_type: UdopUnimodel, 
    architecture_variant: molscribe-encoder-5,
    beam_search: True,
    normalize_bbox: False,

    # Test config
    do_train: False,
    do_eval: False,
    do_predict: True,    
    dataloader_num_workers: 1,
    log_level: "DEBUG",
    viz_out_dir: auto,
    prediction_loss_only: True,
    label_names: ["labels"],      
    unit: word, # word, token
    apply_ocr: False,
}
